[[headers]]
  for = "/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"
    Content-Encoding = "gzip" # ファイルが圧縮されている場合のみ

[[headers]]
  for = "/*.gz"
  [headers.values]
    Content-Encoding = "gzip"

コードをコピーする
[[headers]]
  for = "/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"
    Content-Encoding = "br"  # Brotli圧縮の場合

[[headers]]
  for = "/*.br"
  [headers.values]
    Content-Encoding = "br"
